import { TMDB_API_BASE_URL } from '@/lib/constants'
import type { paths } from '@/types/schema/tmdb-api-schema' // generated by openapi-typescript
import type {
  HTTPMethodPaths,
  OmitResponses,
  OmitUndefinedSubsets,
  TmdbHTTPMethods,
} from '@/types/utils'

export function constructTmdbRequestArguments<
  M extends TmdbHTTPMethods,
  P extends HTTPMethodPaths<M>,
  A extends OmitUndefinedSubsets<OmitResponses<paths[P][Lowercase<M>]>> =
    OmitUndefinedSubsets<OmitResponses<paths[P][Lowercase<M>]>>,
>(method: M, path: P, args?: A): Parameters<typeof fetch> {
  let input: string = TMDB_API_BASE_URL.concat(path)
  const init: RequestInit = {
    method: method,
  }

  if (args) {
    if ('query' in args.parameters && undefined !== args.parameters.query) {
      const queryEntries = Object.entries(args.parameters.query)
      for (const entry of queryEntries) {
        const [k, v] = entry
        if (queryEntries.indexOf(entry) === 0) {
          input = input.concat(`?${k}`, `=${v}`)
        } else {
          input = input.concat(`&${k}`, `=${v}`)
        }
      }
    }
    if ('path' in args.parameters) {
      for (const [k, v] of Object.entries(args.parameters.path)) {
        input = input.replace(`{${k}}`, `${v}`)
      }
    }
    if ('header' in args.parameters) {
    }
    if (
      'requestBody' in args &&
      undefined !== args.requestBody &&
      args.requestBody.content &&
      undefined !== args.requestBody.content['application/json'].RAW_BODY
    ) {
    }
  }

  return [input, init]
}
