import { TMDB_API_BASE_URL } from '@/lib/constants'
import type { paths } from '@/types/schema/tmdb-api-schema' // generated by openapi-typescript
import type {
  HTTPMethodPaths,
  OmitResponses,
  OmitUndefinedSubsets,
  TmdbHTTPMethods,
} from '@/types/utils'

export function constructTmdbRequest<
  M extends TmdbHTTPMethods,
  P extends HTTPMethodPaths<M>,
  A extends OmitUndefinedSubsets<OmitResponses<paths[P][Lowercase<M>]>> =
    OmitUndefinedSubsets<OmitResponses<paths[P][Lowercase<M>]>>,
>(method: M, path: P, args?: A) {
  // todo: args & return type
  if (args) {
    if ('query' in args.parameters) {
    }
    if ('path' in args.parameters) {
    }
    if ('header' in args.parameters) {
    }
    if (
      'requestBody' in args &&
      undefined !== args.requestBody &&
      args.requestBody.content &&
      undefined !== args.requestBody.content['application/json'].RAW_BODY
    ) {
    }
  }

  const req = fetch(`${TMDB_API_BASE_URL}${path}`, {
    method,
  })

  return req
}
